# -*- coding: utf-8 -*-
"""CSES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQ0qnNvaF5dxbY-bVVFEojgahdsL6uHs
"""

n=input()
current=1
lst=[]
maxc=0
for x in n:
    lst.append(x)
for i in range(1,len(lst)):
    if lst[i]==lst[i-1]:
        current+=1
    else:
        maxc=max(current,maxc)
        current=1
print(max(maxc,current))